# Generated by Django 5.1.4 on 2025-03-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-date"],
                "verbose_name": "платеж",
                "verbose_name_plural": "платежи",
            },
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="owner",
            new_name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Статус платежа"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("ONLINE", "Банковский перевод"), ("CASH", "Наличными")],
                default="Банковский перевод",
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
